# RT-Thread building script for component

Import('rtconfig')
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
env_src = ['env/init.c', 'env/start.S']
drv_src = Glob("drivers/*.c")
app_src = Glob("applications/*.c")

src = env_src + drv_src + app_src

CPPPATH = [ cwd + '/include']

CPPDEFINES = []

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
